name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup SDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build project with Maven
      run: mvn -B package shade:shade --file app/pom.xml
    
    - name: Build Binary
      run: cd app/target && zip deployment.zip *-SNAPSHOT.jar

    - name: Path
      run: echo $PWD
      
  # deploy:
  #   name: deploy lambda function
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: AWS Lambda Deploy
  #     if: github.ref == 'refs/heads/master'
  #     uses: appleboy/lambda-action@v0.1.9
  #     with:
  #       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws_region: ${{ secrets.AWS_REGION }}
  #       function_name: gorush
  #       zip_file: output.zip
  #       dry_run: true
